### ISSUE TITLE
Configuration when having locally stored /Assets/ images

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#3]
Hi,

what is the configuration required if you also have images stored in the web project f.ex. /Asstes/myImage.jpg

Also, if you have images configured using this Provider and at the same time use the ImageProcessor CloudImageService, images are throwing 404 is you don't supply querystring parameters.

What are your thoughts on this?

**Comment by perosb** [comment]
Also, I seem to be getting a lot of 502 Gateway using the CloudImageService, I guess there is something when it tries to grab the image from Blob storage.

**Comment by JimBobSquarePants** [comment]
Hi,

This is designed for use with the media section of an Umbraco site only. What is your setup situation?

Do you have RAMMFAR enabled? That might be causing ImageProcessor to kick in when it shouldn't.

**Comment by idseefeld** [comment]
This package is just an implementation of Umbracos IFileSystemProvider. Currently Umbraco only provides this for the media section. 

There is a new Azure provider, maybe this is what you are looking for: https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure

**Comment by perosb** [comment]
@idseefeld Right, that's were we are now ;)

**Comment by perosb** [comment]
@JimBobSquarePants Yes, it is enabled and ImageProcessor is last in the list.

**Comment by JimBobSquarePants** [comment]
A 502 is an error with Azure, not with ImageProcessor. All I'm doing internally is a http request.

**Comment by JimBobSquarePants** [comment]
Hmmm.. I'll have to experiment. ImageProcessor should be ignoring no querystring based paths.

**Comment by perosb** [comment]
@JimBobSquarePants Right, maybe it is possible to add some fault tolerance or similar. It usually works jjust reloading the image.

Also, when requesting /Assets/myimage.png without querystring, it returns the image, but since there is only a single service, CloudService enabled, adding querystrings throws 400 Bad Request.

**Comment by JimBobSquarePants** [comment]
Feel free to do so.... ;)

Damn RAMMFAR. It should never really be enabled since its a performance hog. I'll have to have a look at what is going on. It won't be til the weekend though I'm afraid, super swamped.

**Comment by JimBobSquarePants** [comment]
Actually this is ok. :smile: 

You can combine the two `IImagService` implementations if you add a prefix value to the `CloudImageService` and expand the `Host` property to match. I tested the following configuration and it worked well. I'll update the readme and MyGetPackages.

```xml
<?xml version="1.0"?>
<security>
  <services>
    <service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web"/>
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://[myAccountName].blob.core.windows.net/media/"/>
      </settings>
    </service>
</security>
```

**Comment by perosb** [comment]
Ah, thanks! Thats clever with the Host.
I had a different solution using CloudFront, where you also can set a "Prefix" which should match the CloudService prefix.

**Comment by perosb** [comment]
@JimBobSquarePants Sorry to open this again.

Regarding the 502 Gateway issue, could it be related to
`System.IO.IOException: The process cannot access the file 'D:\home\site\wwwroot\app_data\cache\0\6\5\f\2\7\065f27fc2c8e843443d210a1e84d1ea28bbab6c4.webp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at ImageProcessor.Web.Caching.DiskCache.<AddImageToCacheAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)`

I'm seeing this issue intermittently and it might be happening at the same time.

**Comment by JimBobSquarePants** [comment]
No worries... 

This really belongs on the ImageProcessor bug tracker though so could you resubmit it?

Also let me double check.

You are storing your images in the cloud but caching them on disk and you're also using the webp plugin?

Out of curiosity, how come you're using the disk cache and not the Azure cache?

**Comment by perosb** [comment]
Thanks. I have raised an issue https://github.com/JimBobSquarePants/ImageProcessor/issues/189 for ImageProcessor.

Also moved over to the Azure blob cache, with StreamCachedImage = true.
Lets see if the errors continues.
