### ISSUE TITLE
Getting Forbidden 403 for file types out of blue

### ISSUE THREAD

**Issue by akeilox** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#63]
Without changing any configuration both on Umbraco and Azure, I start getting 403 for media file types (.xls, .pdf etc.).

I have checked the connection string (primary) on azure and compared against FileSystemProviders.config and they are identical; i.e. no changes whatsoever to the Umbraco installation, or in Azure.

The log shows the following:
2016-10-18 14:48:18,535 [7] ERROR Umbraco.Core.UmbracoApplicationBase - [Thread 25] An unhandled exception occurred
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Our.Umbraco.FileSystemProviders.Azure.AzureFileSystem.FileExists(String path)
   at System.Web.Routing.RouteCollection.IsRouteToExistingFile(HttpContextBase httpContext)
   at System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
Request Information
RequestID:e1c47e5a-0001-0049-020d-2945ff000000
RequestDate:Tue, 18 Oct 2016 07:03:30 GMT
StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by akeilox** [comment]
I would like to add there is also no change to IIS (http/https etc).
nor umbraco config.

Been running without issues till the 403 forbidden start appearing today.

Running Umbraco 7.2 on Windows 2008 R2

**Comment by JimBobSquarePants** [comment]
Try checking your server time. That's the only thing I can think of.

http://stackoverflow.com/questions/22828279/403-error-in-production-from-windowsazure-storage

**Comment by akeilox** [comment]
@JimBobSquarePants that was it, sites running inside a virtual machine with vmware's time drifting issue got hit by this.

Many thanks @JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
Sweet! Great to hear!
