### ISSUE TITLE
Cannot visit Umbraco page at /media/

### ISSUE THREAD

**Issue by tomfulton** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#8]
If you are using this package and have the Virtual Path Provider configured, and you have a page at the root of your Umbraco site called "Media" (/media/), you will receive this exception when trying to visit the page:

```
System.ArgumentException: The argument must not be empty string.
Parameter name: blobName
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpty(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.GetBlockBlobReference(String blobName, Nullable`1 snapshotTime)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.GetBlockBlobReference(String blobName)
   at Our.Umbraco.FileSystemProviders.Azure.AzureFileSystem.GetBlockBlobReference(String path) in J:\Dev\Projects\UmbracoFileSystemProviders.Azure\src\UmbracoFileSystemProviders.Azure\AzureFileSystem.cs:line 526
   at Our.Umbraco.FileSystemProviders.Azure.AzureFileSystem.FileExists(String path) in J:\Dev\Projects\UmbracoFileSystemProviders.Azure\src\UmbracoFileSystemProviders.Azure\AzureFileSystem.cs:line 330
   at Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem.FileExists(String path) in J:\Dev\Projects\UmbracoFileSystemProviders.Azure\src\UmbracoFileSystemProviders.Azure\AzureBlobFileSystem.cs:line 132
   at Our.Umbraco.FileSystemProviders.Azure.FileSystemVirtualPathProvider.FileExists(String virtualPath) in J:\Dev\Projects\UmbracoFileSystemProviders.Azure\src\UmbracoFileSystemProviders.Azure\FileSystemVirtualPathProvider.cs:line 125
   at System.Web.Routing.RouteCollection.IsRouteToExistingFile(HttpContextBase httpContext)
   at System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

I'm assuming this is some conflict with the VirtualPathProvider, but I'm not quite sure what the fix would be (if any).  Could it perhaps ignore itself and only kick in for requests beneath it?  (ie /media/*)

**Comment by JimBobSquarePants** [comment]
That's kinda expected at the moment. The VirtualPathProvider will be intercepting all calls. 

I think we'll have to have a look at integrating the VirtualPathProvider more closely with Umbraco as that would probably allow us allow this. If you have the opportunity to do so, that would be ace.

**Comment by idseefeld** [comment]
Hi James,
I have talked to Shannon and Morten at CodeGarden about the VirtualPathProvider idea. I remember Shannon was not very fond of it. He mentioned it is quite old and tricky to handle. I suggested a different approach via routing. But I could not firgure it out later on - so I may have misunderstood him. Sorry, I am not familiar with all this routing stuff :-(
Reading this I think the whole topic should be fore the core. At least we should ask them for advice or start a discussion on https://groups.google.com/forum/#!forum/umbraco-dev. Probably core team needs a proper solution for Umbraco.com (UaaS) too.

Thank you for all your effort and engagement! Great job!

**Comment by Slowacki** [comment]
Hey guys, is there any progress on this issue? It's not breaking, but it is mildly annoying because of all the errors it's creating in our logs.

**Comment by JimBobSquarePants** [comment]
Nope, and none that can be made as far as I know.

**Comment by JimBobSquarePants** [comment]
I just had another dig through the codebase and refactored the method calls to not throw when there is no file. This should finally fix this longstanding issue.

**Comment by Slowacki** [comment]
Coolio, good job and thanks!
